server:
  port: 9100  

spring:
  application:
    name: cloud-gateway 
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:8090/auth/realms/dan-realm   


    
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/usuario/**
          filters:
            - StripPrefix=1
        - id: material
          uri: lb://material
          predicates:
            - Path=/material/**        
          filters:
            - StripPrefix=1
        - id: pedido
          uri: lb://pedido
          predicates:
            - Path=/pedido/**
          filters:
            - StripPrefix=1
        - id: cuenta
          uri: lb://cuenta
          predicates:
            - Path=/cuenta/**
          filters:
            - StripPrefix=1
        - id: blog
          uri: lb://blog
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1
               

  
eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
      
management.endpoint.metrics.enabled: true
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management.endpoints.web.exposure.include: "*"
    
     
       

      
      

